/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Consumption {
	details?: Array<Array<string>>;
	month?: number;
	nbUnits?: number;
	organisationId?: string;
	organizationName?: string;
	productName?: string;
	productType?: Consumption.ProductTypeEnum;
	ratePlanId?: string;
	year?: number;
}
export namespace Consumption {
	export type ProductTypeEnum =
		| 'SIGNATURE'
		| 'SERVER_STAMP'
		| 'TIMESTAMPING'
		| 'TRANSACTIONS'
		| 'GENERIC'
		| 'CPM'
		| 'PRESTA'
		| 'OED_SETUP'
		| 'OED_RUN'
		| 'FORFAIT';
	export const ProductTypeEnum = {
		SIGNATURE: 'SIGNATURE' as ProductTypeEnum,
		SERVERSTAMP: 'SERVER_STAMP' as ProductTypeEnum,
		TIMESTAMPING: 'TIMESTAMPING' as ProductTypeEnum,
		TRANSACTIONS: 'TRANSACTIONS' as ProductTypeEnum,
		GENERIC: 'GENERIC' as ProductTypeEnum,
		CPM: 'CPM' as ProductTypeEnum,
		PRESTA: 'PRESTA' as ProductTypeEnum,
		OEDSETUP: 'OED_SETUP' as ProductTypeEnum,
		OEDRUN: 'OED_RUN' as ProductTypeEnum,
		FORFAIT: 'FORFAIT' as ProductTypeEnum
	};
}
