/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntityCrm } from './entityCrm';
import { NameCrm } from './nameCrm';
import { UserCrm } from './userCrm';

export interface ContactCrm {
	accounts?: Array<EntityCrm>;
	contactedCount?: number;
	createdDate?: Date;
	creator?: UserCrm;
	deletedTime?: Date;
	description?: string;
	id?: number;
	jobTitle?: string;
	modifiedDate?: Date;
	name?: string;
	names?: NameCrm;
	relationship?: string;
}
