/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InvoiceItem } from './invoiceItem';
import { Payment } from './payment';
import { PaymentMethod } from './paymentMethod';
import { Refund } from './refund';

export interface Invoice {
	additionalItems?: Array<InvoiceItem>;
	comments?: string;
	creditNoteSendDate?: Date;
	customerId?: string;
	customerName?: string;
	dateToSend?: Date;
	dueDate?: Date;
	dunningSendDate?: Date;
	emissionDate?: Date;
	humanId?: string;
	id?: string;
	items?: Array<InvoiceItem>;
	message?: string;
	month?: number;
	payment?: Payment;
	paymentMethod?: PaymentMethod;
	paymentsHistoric?: Array<Payment>;
	pdfFileName?: string;
	purchaseOrder?: string;
	refund?: Refund;
	refundAmount?: number;
	sendDate?: Date;
	status?: Invoice.StatusEnum;
	total?: number;
	totalPriceGross?: number;
	type?: Invoice.TypeEnum;
	validated?: boolean;
	validationDate?: Date;
	validatorId?: string;
	vat?: number;
	year?: number;
}
export namespace Invoice {
	export type StatusEnum =
		| 'DRAFT'
		| 'CREATED'
		| 'VALIDATED'
		| 'INVALIDATED'
		| 'SENT'
		| 'PAID'
		| 'UNPAID'
		| 'REFUNDED';
	export const StatusEnum = {
		DRAFT: 'DRAFT' as StatusEnum,
		CREATED: 'CREATED' as StatusEnum,
		VALIDATED: 'VALIDATED' as StatusEnum,
		INVALIDATED: 'INVALIDATED' as StatusEnum,
		SENT: 'SENT' as StatusEnum,
		PAID: 'PAID' as StatusEnum,
		UNPAID: 'UNPAID' as StatusEnum,
		REFUNDED: 'REFUNDED' as StatusEnum
	};
	export type TypeEnum = 'INVOICE' | 'INVOICE_ONE_SHOT' | 'REFUND';
	export const TypeEnum = {
		INVOICE: 'INVOICE' as TypeEnum,
		INVOICEONESHOT: 'INVOICE_ONE_SHOT' as TypeEnum,
		REFUND: 'REFUND' as TypeEnum
	};
}
