/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';

export interface InvoiceItem {
	discount?: number;
	globalQuantity?: number;
	itemType?: InvoiceItem.ItemTypeEnum;
	maxStep?: number;
	minStep?: number;
	name?: string;
	price?: number;
	product?: Product;
	quantity?: number;
	unitPrice?: number;
	untilDate?: Date;
}
export namespace InvoiceItem {
	export type ItemTypeEnum = 'SUBSCRIPTION' | 'STEP' | 'FREE_UNITS' | 'CUSTOM';
	export const ItemTypeEnum = {
		SUBSCRIPTION: 'SUBSCRIPTION' as ItemTypeEnum,
		STEP: 'STEP' as ItemTypeEnum,
		FREEUNITS: 'FREE_UNITS' as ItemTypeEnum,
		CUSTOM: 'CUSTOM' as ItemTypeEnum
	};
}
