/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Organization {
	addr?: string;
	city?: string;
	country?: string;
	createdAt?: Date;
	details?: string;
	domainNames?: Array<string>;
	externalId?: string;
	groupId?: number;
	id?: number;
	individual?: boolean;
	ipRanges?: string;
	name?: string;
	notes?: string;
	organizationFields?: any;
	registerDate?: Date;
	sharedComments?: boolean;
	sharedTickets?: boolean;
	status?: number;
	tags?: Array<string>;
	updatedAt?: Date;
	vatNumber?: string;
	zipCode?: string;
}
