/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Links } from './links';

export interface Payment {
	amount?: number;
	amountRefunded?: number;
	chargeDate?: string;
	createdAt?: string;
	currency?: Payment.CurrencyEnum;
	description?: string;
	id?: string;
	links?: Links;
	metadata?: { [key: string]: string };
	reference?: string;
	status?: Payment.StatusEnum;
}
export namespace Payment {
	export type CurrencyEnum = 'AUD' | 'CAD' | 'DKK' | 'EUR' | 'GBP' | 'NZD' | 'SEK';
	export const CurrencyEnum = {
		AUD: 'AUD' as CurrencyEnum,
		CAD: 'CAD' as CurrencyEnum,
		DKK: 'DKK' as CurrencyEnum,
		EUR: 'EUR' as CurrencyEnum,
		GBP: 'GBP' as CurrencyEnum,
		NZD: 'NZD' as CurrencyEnum,
		SEK: 'SEK' as CurrencyEnum
	};
	export type StatusEnum =
		| 'PENDING_CUSTOMER_APPROVAL'
		| 'PENDING_SUBMISSION'
		| 'SUBMITTED'
		| 'CONFIRMED'
		| 'PAID_OUT'
		| 'CANCELLED'
		| 'CUSTOMER_APPROVAL_DENIED'
		| 'FAILED'
		| 'CHARGED_BACK';
	export const StatusEnum = {
		PENDINGCUSTOMERAPPROVAL: 'PENDING_CUSTOMER_APPROVAL' as StatusEnum,
		PENDINGSUBMISSION: 'PENDING_SUBMISSION' as StatusEnum,
		SUBMITTED: 'SUBMITTED' as StatusEnum,
		CONFIRMED: 'CONFIRMED' as StatusEnum,
		PAIDOUT: 'PAID_OUT' as StatusEnum,
		CANCELLED: 'CANCELLED' as StatusEnum,
		CUSTOMERAPPROVALDENIED: 'CUSTOMER_APPROVAL_DENIED' as StatusEnum,
		FAILED: 'FAILED' as StatusEnum,
		CHARGEDBACK: 'CHARGED_BACK' as StatusEnum
	};
}
