/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductSetting } from './productSetting';

export interface Product {
	commercialName?: string;
	description?: string;
	id?: string;
	lastUpdate?: Date;
	matrix?: Array<Array<number>>;
	name?: string;
	productType?: Product.ProductTypeEnum;
	settings?: Array<ProductSetting>;
}
export namespace Product {
	export type ProductTypeEnum =
		| 'SIGNATURE'
		| 'SERVER_STAMP'
		| 'TIMESTAMPING'
		| 'TRANSACTIONS'
		| 'GENERIC'
		| 'CPM'
		| 'PRESTA'
		| 'OED_SETUP'
		| 'OED_RUN'
		| 'FORFAIT';
	export const ProductTypeEnum = {
		SIGNATURE: 'SIGNATURE' as ProductTypeEnum,
		SERVERSTAMP: 'SERVER_STAMP' as ProductTypeEnum,
		TIMESTAMPING: 'TIMESTAMPING' as ProductTypeEnum,
		TRANSACTIONS: 'TRANSACTIONS' as ProductTypeEnum,
		GENERIC: 'GENERIC' as ProductTypeEnum,
		CPM: 'CPM' as ProductTypeEnum,
		PRESTA: 'PRESTA' as ProductTypeEnum,
		OEDSETUP: 'OED_SETUP' as ProductTypeEnum,
		OEDRUN: 'OED_RUN' as ProductTypeEnum,
		FORFAIT: 'FORFAIT' as ProductTypeEnum
	};
}
