/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SatisfactionRating {
	assigneeId?: number;
	comment?: string;
	createdAt?: Date;
	groupId?: number;
	id?: number;
	reason?: string;
	reasonId?: number;
	requesterId?: number;
	score?: string;
	ticketId?: number;
	updatedAt?: Date;
	url?: string;
}
