/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountCrm } from './accountCrm';
import { ContactCrm } from './contactCrm';
import { LeadCrm } from './leadCrm';

export interface SearchResponse {
	accounts?: Array<AccountCrm>;
	contacts?: Array<ContactCrm>;
	leads?: Array<LeadCrm>;
}
