/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Locale } from './locale';
import { SettingsInvoiceUnit } from './settingsInvoiceUnit';

export interface SettingsInvoice {
	billingActive?: boolean;
	detailSkipped?: boolean;
	fullyAutomatic?: boolean;
	global?: SettingsInvoiceUnit;
	locale?: Locale;
	manualBillingOnly?: boolean;
	paymentTerms?: string;
	perOrganization?: boolean;
	period?: SettingsInvoice.PeriodEnum;
	subscription?: Array<SettingsInvoiceUnit>;
	taxPerCent?: number;
}
export namespace SettingsInvoice {
	export type PeriodEnum = 'MONTHLY' | 'QUARTERLY' | 'ANNUAL';
	export const PeriodEnum = {
		MONTHLY: 'MONTHLY' as PeriodEnum,
		QUARTERLY: 'QUARTERLY' as PeriodEnum,
		ANNUAL: 'ANNUAL' as PeriodEnum
	};
}
