/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InvoiceItem } from './invoiceItem';
import { Organization } from './organization';
import { RatePlan } from './ratePlan';
import { SubscriptionFeature } from './subscriptionFeature';

export interface Subscription {
	commercialName?: string;
	description?: string;
	freeMonths?: number;
	id?: string;
	invoiceItemDateds?: Array<InvoiceItem>;
	lastUpdate?: Date;
	name?: string;
	ratePlans?: Array<RatePlan>;
	subscriptionFeatures?: Array<SubscriptionFeature>;
	usages?: Array<Organization>;
	version?: string;
}
