/**
 * REST API For Vision 360
 * API in front of CRM (Nutshell) PPM(Clarizen) and billing
 *
 * OpenAPI spec version: 1.0
 * Contact: eric.lamore@universsign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserCrm {
	administrator?: boolean;
	createdDate?: Date;
	createdTime?: Date;
	deletedTime?: Date;
	description?: string;
	emails?: Array<string>;
	enabled?: boolean;
	firstName?: string;
	id?: number;
	lastName?: string;
	modifiedDate?: Date;
	modifiedTime?: Date;
	name?: string;
}
